# Generated by Django 3.0.5 on 2020-04-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=30)),
                ('typewriter', models.BooleanField(default=True)),
                ('image', models.ImageField(max_length=255, upload_to='billboard/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('catid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline1', models.CharField(max_length=20)),
                ('headline2', models.CharField(max_length=20)),
                ('headline3', models.CharField(max_length=20)),
                ('image1', models.ImageField(max_length=255, upload_to='services/')),
                ('image2', models.ImageField(max_length=255, upload_to='services/')),
                ('image3', models.ImageField(max_length=255, upload_to='services/')),
                ('text1', models.CharField(max_length=50)),
                ('text2', models.CharField(max_length=50)),
                ('text3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image1', models.ImageField(max_length=255, upload_to='products/')),
                ('image2', models.ImageField(max_length=255, upload_to='products/')),
                ('image3', models.ImageField(max_length=255, upload_to='products/')),
                ('description', models.TextField()),
                ('subtitle', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
