# Generated by Django 3.0.5 on 2020-04-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='headline_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billboard',
            name='headline_zn_tw',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billboard',
            name='subtitle_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='billboard',
            name='subtitle_zn_tw',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_zn_tw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_zn_tw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_zn_tw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_zn_tw',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='headline1_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='headline1_zn_tw',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='headline2_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='headline2_zn_tw',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='headline3_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='headline3_zn_tw',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text1_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text1_zn_tw',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text2_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text2_zn_tw',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text3_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text3_zn_tw',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
