# Generated by Django 3.0.5 on 2020-04-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200428_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billboard',
            old_name='headline_zn_tw',
            new_name='headline_zh_tw',
        ),
        migrations.RenameField(
            model_name='billboard',
            old_name='subtitle_zn_tw',
            new_name='subtitle_zh_tw',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_zn_tw',
            new_name='category_zh_tw',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_zn_tw',
            new_name='description_zh_tw',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_zn_tw',
            new_name='name_zh_tw',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subtitle_zn_tw',
            new_name='subtitle_zh_tw',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='headline1_zn_tw',
            new_name='headline1_zh_tw',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='headline2_zn_tw',
            new_name='headline2_zh_tw',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='headline3_zn_tw',
            new_name='headline3_zh_tw',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='text1_zn_tw',
            new_name='text1_zh_tw',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='text2_zn_tw',
            new_name='text2_zh_tw',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='text3_zn_tw',
            new_name='text3_zh_tw',
        ),
    ]
