# Generated by Django 3.0.5 on 2020-04-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200428_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='AboutUs',
        ),
    ]
