# Generated by Django 3.0.5 on 2020-05-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200428_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='headline1',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='headline1_en',
            new_name='headline_en',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='headline1_zh_tw',
            new_name='headline_zh_tw',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='text1',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='text1_en',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='text1_zh_tw',
            new_name='text_zh_tw',
        ),
        migrations.RemoveField(
            model_name='services',
            name='headline2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='headline2_en',
        ),
        migrations.RemoveField(
            model_name='services',
            name='headline2_zh_tw',
        ),
        migrations.RemoveField(
            model_name='services',
            name='headline3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='headline3_en',
        ),
        migrations.RemoveField(
            model_name='services',
            name='headline3_zh_tw',
        ),
        migrations.RemoveField(
            model_name='services',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='text2_en',
        ),
        migrations.RemoveField(
            model_name='services',
            name='text2_zh_tw',
        ),
        migrations.RemoveField(
            model_name='services',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='text3_en',
        ),
        migrations.RemoveField(
            model_name='services',
            name='text3_zh_tw',
        ),
    ]
