# Generated by Django 3.0.5 on 2020-05-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200501_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='maintext',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='maintext_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='maintext_zh_tw',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='headline',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='headline_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='headline_zh_tw',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='subtitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='subtitle_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='subtitle_zh_tw',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='headline',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='headline_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='headline_zh_tw',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='text_zh_tw',
            field=models.TextField(null=True),
        ),
    ]
