# Generated by Django 3.0.5 on 2020-05-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200512_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catid',
            field=models.CharField(help_text="The following categories are available: 'bicycle' for bicycle products, 'cutlery' for cutlery, 'toys' for toys, 'cups' for coffee cups and 'packaging' for packaging. Want another category added? Contact Glenn.", max_length=100),
        ),
    ]
